### ISSUE TITLE
Different face detector

### ISSUE THREAD

**Issue by sbharadwajj** [HSE-asavchenko/HSE_FaceRec_tf#1]
@HSE-asavchenko Can a different face detector be used instead of mtcnn?

**Comment by av-savchenko** [comment]
Yes, sure, any appropriate detector should work. The detect_face() method in the file “age_gender_identity/facial_analysis.py” contains the part for OpenCV detector if mtcnn_detector parameter in FacialImageProcessing constructor was set to False. In the latter case you have to copy file 'haarcascade_frontalface_alt2.xml’ to your directory. I also tried custom Faster R-CNN-based detectors, and the face processing quality has remains rather high

**Comment by sbharadwajj** [comment]
I tried running the file without loading the mtcnn.pb file and got an error even though I have loaded the `age_gender_tf2_new-01-0.14-0.92.pb` file.
error:
`KeyError: "The name 'age_pred/Softmax:0' refers to a Tensor which does not exist. The operation, 'age_pred/Softmax', does not exist in the graph."`

But this cant happen because I have not loaded the mtcnn.pb file, right?

**Comment by av-savchenko** [comment]
I just added LBP face detector from OpenCV to my code and successfully launched “python facial_analysis.py” in order to work with the video from web-camera. Could you verify that your error appears if you simply replace “mtcnn_detector=True” to “mtcnn_detector=False”  and run facial_analysis.py without parameters?

**Comment by sbharadwajj** [comment]
Hi, it is my fault. I hadn't defined the graph properly. It has loaded now. Thank you!
