### ISSUE TITLE
Question: How does these models compare to your other efficientNet-based models ?

### ISSUE THREAD

**Issue by AGenchev** [HSE-asavchenko/HSE_FaceRec_tf#3]
Hello, I read your article which led me here.
Because at the repo of efficientNet they have graphic which shows their B6, B7 models as far superior to the ResNets in both inference performance and precision, I begun wondering whether this is true. Since you have FaceRec, based on both models, it is interesting how do they compare in your implementation.
I saw that ResNet50 gave you best results for Face identification accuracy, but no results in the "fast-image-recognition" repo are published. Also while I haven't read the code yet, I wonder whether the embedding feature vectors are of the same size and what size did you choose. 
Thanks !

**Comment by av-savchenko** [comment]
Thanks for this question!
Speaking about publications for fast-image-recognition repo, most of them are mentioned [here](https://github.com/HSE-asavchenko/fast-image-recognition/tree/master/qt_cpp) because I mainly used C++ to optimize classification time. However, source code in should refer to [my paper](https://ieeexplore.ieee.org/abstract/document/9207379) at IJCNN20 conference. All my recent papers in image categorization prove that EfficientNets let to extract much better features.
I should clarify that I did not add any layers to original ConvNets pre-trained on ImageNet, so that the size of the feature vectors and even the input size of an image vary. For example, Inception v3 needs 299x299 image to extract 2048 features, EfficientNet-B0 require 224x224 image and extracts 1024-dimensional feature vector, while EfficientNet-B3 uses 300x300 input image and returns 1536 features.
Finally, speaking about current repository, I have not yet trained EfficientNets for face recognition. Hence, my results are reported for existing facial descriptors like VGGFace2 (ResNet-50/SeNet-50). I only trained lightweight MobileNet v1, which is very fast but slightly less accurate than above-mentioned ResNet-50 on typical facial datasets

**Comment by AGenchev** [comment]
Thank you for your answer and links to papers, I'll read them.
I see you wonder which paper I read - it is different, because I was looking for optimized age-gender-race models when I found your article on [multi-output ConvNet](https://peerj.com/articles/cs-197.pdf) where your results are better than my previous favorite (SSR-nets).
About face features, first I see that the models have square inputs, which is general-purpose approach, not face oriented. This makes the researches who use them to stretch the faces in horizontal axis to increase the utilization of the receptive field. 
I've read that when a lower-dimensional embedding layer is **stacked** on the top of the original final feature layer adjacent to classifier, we can get significantly  reduced dimensions, say 128 or 256 while preserving the accuracy. It has been reported [here, on github](https://github.com/ox-vgg/vgg_face2). 
About language - I also don't like python (bad whitespace-syntax, slow), but it has huge fan-base which ports every existing C/C++ written DLL or .so into py modules and then writes examples and advertises that it is easy. There is an attempt to **replace** it with something **better** - the Julia language which is faster, compiled, jupyter-notebook supported (I know people of academic society which are big supporters), but it has not so huge fan base. C++ is fast, pure C is even faster (you don't have classes and VMT/DMT), but researchers mostly do not make production software.
